// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package book_sales_api

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID    int64
	Name  string
	Email string
	Bio   pgtype.Text
}

type Book struct {
	ID   int64
	Name string
}
